from typing import Any
# Language mapping dictionary for medical report
LANGUAGE_MAPPING = {
    "id": {
        "medical_checkup_report": "Medical Check Up Report",
        "patient_identity": "IDENTITAS PASIEN",
        "checkout_examination_date": "Tanggal Pemeriksaan",
        "current_complaints": "KELUHAN SEKARANG",
        "personal_medical_history": "Riwayat Penyakit Sendiri",
        "family_medical_history": "Riwayat Penyakit Keluarga",
        "habits": "Kebiasaan",
        "physical_examination": "PEMERIKSAAN FISIK",
        "vital_signs": "TANDA-TANDA VITAL & VISUS",
        "conclusion": "KESIMPULAN",
        "advice": "SARAN",
        "analysis": "ANALISA",
        "laboratory_test_result": "LABORATORY TEST RESULT",
        "radiology_examination_result": "HASIL PEMERIKSAAN RADIOLOGI",
        "thorax_photo": "THORAX FOTO",
        "result": "Hasil",
        "conclusion_lower": "Kesimpulan",
        "examining_doctor": "Dokter Pemeriksa",
        "laboratory_supervisor": "Penanggung Jawab Laboratorium",
        "examined_by": "Diperiksa Oleh",
        "examination": "PEMERIKSAAN",
        "result_value": "HASIL",
        "unit": "SATUAN",
        "reference_value": "NILAI RUJUKAN",
        "notes": "KETERANGAN",
        "patient_photo": "FOTO PASIEN",
        "examination_result": "Hasil Pemeriksaan:",
        "suggestion": "Saran:",
        "radiological_examination": "Pemeriksaan Radiologi - Rontgen Thorax",
        "electrocardiography": "Pemeriksaan Elektrokardiografi (EKG)",
        "lung_function": "Pemeriksaan Fungsi Paru-Paru - Spirometri",
        "hearing_function": "Pemeriksaan Fungsi Pendengaran - Audiometri",
        "exercise_stress_test": "Pemeriksaan Exercise Stress Test - Treadmill",
        "usg_abdomen": "Pemeriksaan USG Abdomen",
        "usg_mammae": "Pemeriksaan USG Mammae",
        "attachment_note": "(Gambar/grafik terlampir di halaman akhir)",
        "attachment_prefix": "Lampiran ",
        "validation_note": "*Dokumen Hasil Pemeriksaan ini tidak membutuhkan tanda tangan basah karena telah divalidasi dan dihasilkan oleh Sistem Informasi Bumame.",
        "right_ear_ac": "Telinga Kanan (AC)",
        "right_ear_bc": "Telinga Kanan (BC)",
        "left_ear_ac": "Telinga Kiri (AC)",
        "left_ear_bc": "Telinga Kiri (BC)",
        "hz": "Hz",
        "db": "dB",
        # Patient Identity Labels
        "nik": "NIK",
        "name": "Nama",
        "birth_date": "Tanggal Lahir",
        "gender": "Jenis Kelamin",
        "group": "Kelompok",
        # Laboratory Header Labels
        "barcode_sample": "No. Barcode Sample",
        "phone": "Telepon/HP",
        "address": "Alamat",
        "examination_date": "Tanggal Periksa",
        "specimen_location": "Lokasi Pengambilan Spesimen",
        "birth_date_short": "Tgl. Lahir"
    },
    "en": {
        "medical_checkup_report": "Medical Check Up Report",
        "checkout_examination_date": "Examination Date",
        "patient_identity": "PATIENT IDENTITY",
        "current_complaints": "CURRENT COMPLAINTS",
        "personal_medical_history": "Personal Medical History",
        "family_medical_history": "Family Medical History",
        "habits": "Habits",
        "physical_examination": "PHYSICAL EXAMINATION",
        "vital_signs": "VITAL SIGNS",
        "conclusion": "CONCLUSION",
        "advice": "RECOMMENDATION",
        "analysis": "ANALYSIS",
        "laboratory_test_result": "LABORATORY TEST RESULT",
        "radiology_examination_result": "RADIOLOGY EXAMINATION RESULT",
        "thorax_photo": "CHEST X-RAY",
        "result": "Result",
        "conclusion_lower": "Conclusion",
        "examining_doctor": "Examiner",
        "laboratory_supervisor": "Laboratory Supervisor",
        "examined_by": "Examined By",
        "examination": "EXAMINATION",
        "result_value": "RESULT",
        "unit": "UNIT",
        "reference_value": "REFERENCE VALUE",
        "notes": "NOTES",
        "patient_photo": "PATIENT PHOTO",
        "examination_result": "Examination Result:",
        "suggestion": "Recommendation:",
        "radiological_examination": "Radiological Examination - Chest X-Ray",
        "electrocardiography": "Electrocardiography (ECG)",
        "lung_function": "Pulmonary Function Test - Spirometry",
        "hearing_function": "Hearing Function Test - Audiometry",
        "exercise_stress_test": "Exercise Stress Test - Treadmill",
        "usg_abdomen": "Abdominal Ultrasound Examination",
        "usg_mammae": "Breast Ultrasound Examination",
        "attachment_note": "(Image/chart attached at the end of document)",
        "attachment_prefix": "Attachment ",
        "validation_note": "*This Examination Result Document does not require a wet signature as it has been validated and generated by the Bumame Information System.",
        "right_ear_ac": "Right Ear (AC)",
        "right_ear_bc": "Right Ear (BC)",
        "left_ear_ac": "Left Ear (AC)",
        "left_ear_bc": "Left Ear (BC)",
        "hz": "Hz",
        "db": "dB",
        # Patient Identity Labels
        "nik": "NIK",
        "name": "Name",
        "birth_date": "Date of Birth",
        "gender": "Gender",
        "group": "Group",
        # Laboratory Header Labels
        "barcode_sample": "Barcode Sample No.",
        "phone": "Phone",
        "address": "Address",
        "examination_date": "Examination Date",
        "specimen_location": "Specimen Collection Location",
        "birth_date_short": "Date of Birth",
    }
}

LANGUAGE_MAPPING_SATUAN = {
    "id": {
       
    },
    "en": {
        "kali / minggu": "times / week",
        "Obesitas": "Obesity",
        "Kelas": "Class",
        "Lainnya": "Other",
        "Kurang dari": "Less than",
        "Lebih dari": "More than",
        "batang / hari": "sticks / day",
        "mm/jam": "mm/h",
        "Positif": "Positive",
    }
}

LANGUAGE_LAB_MAPPING_SATUAN = {
    "id": {
       
    },
    "en": {
        "Negatif": "Negative",
        "Positif": "Positive",
        "Kuning": "Yellow",
        "Keruh": "Cloudy",
        "Jernih": "Clear",
        "mm/jam": "mm/h",
    }
}

LANGUAGE_MAPPING_ANSWER = {
    "id": {
        "Yes": "Ya",
        "No": "Tidak",
        "Negative": "Negatif",
        "Positive": "Positif",
    },
    "en": {
        "Tidak": "No",
        "Ya": "Yes",
        "Tidak Ada": "No",
        "Ada": "Yes",
        "Tidak Normal": "Not Normal",
        "Dari Ibu": "From Mother",
        "Dari Ayah": "From Father",
        "Dari Ayah & Ibu": "From Father and Mother",
    }
}

PRESCREENING_TEST_MAPPING = {
    "id" : {

    }, 
    "en" : {
        "Minum Alkohol": "Alcohol Consumption",
        "Merokok": "Smoking",
        "Olahraga": "Exercise",
        "Jenis Olahraga": "Type of Exercise",
        "Olahraga Berapa kali per minggu": "Exercise Frequency per Week",
        "Vape / Rokok Elektrik": "Vape / Electric Cigarette",
        "Riwayat Penyakit Jantung": "Family History of Heart Disease",
        "Riwayat Hipertensi/Darah Tinggi": "Family History of Hypertension",
        "Riwayat Kencing Manis/Diabetes": "Family History of Diabetes",
        "Riwayat Stroke": "Family History of Stroke",
        "Riwayat Penyakit Paru/Asma/TBC": "Family History of Lung Disease / Asthma / TB",
        "Riwayat Kanker/Tumor": "Family History of Cancer / Tumor",
        "Riwayat Penyakit Gangguan Jiwa": "Family History of Mental Illness",
        "Riwayat Penyakit Ginjal": "Family History of Kidney Disease",
        "Riwayat Penyakit Saluran Pencernaan": "Family History of Digestive Disorders",
        "Riwayat Hepatitis": "History of Hepatitis",
        "Riwayat Pengobatan TBC": "History of TB Treatment",
        "Hipertensi / Darah Tinggi": "History of Hypertension / High Blood Pressure",
        "Kencing Manis / Diabetes": "History of Diabetes Mellitus",
        "Batuk Menahun": "History of Chronic Cough",
        "Riwayat Operasi": "Surgical History",
        "Riwayat Rawat Inap 1 tahun terakhir": "Hospitalization in the Last Year",
        "Riwayat Alergi Obat/Makanan/Lainnya": "History of Drug/Food/Other Allergies",
        "Riwayat Kesehatan lain-lain": "Other Health History",
    }
}

PEMFIS_TEST_MAPPING = {
    "id" : {

    }, 
    "en" : {
        "Kepala dan Sistem Endokrin": "Head and Endocrine System",
        "Pemeriksaan Umum":"General Examination",
        "Mata dan Penglihatan":"Eyes and Vision",
        "Telinga, Hidung, dan Tenggorokan":"Ears, Nose, and Throat (ENT)",
        "Gigi":"Teeth",
        "Sistem Kardiopulmonal":"Cardiopulmonary System",
        "Sistem Pencernaan dan Urologi":"Digestive and Urological System",
        "Muskuloskeletal dan Neurologis":"Musculoskeletal and Neurological System",

        "Kulit": "Skin",
        "Keadaan Umum": "General Condition", 
        "Status Mental": "Mental Status",
        "Mata": "Eyes",
        "Kelainan Mata": "Eye Abnormalities",
        "Telinga": "Ears",
        "Hidung": "Nose",
        "Tenggorokan": "Throat",
        "Sinus": "Sinus",
        "Tonsil": "Tonsils",
        "Gigi": "Teeth",
        "Kepala & Leher": "Head & Neck",
        "Kelenjar Limfe": "Lymph Nodes",
        "Kelenjar Tiroid/Gondok": "Thyroid/Gland",
        "Dada": "Chest",
        "Jantung": "Heart",
        "Paru": "Lungs",
        "Abdomen": "Abdomen",
        "Perabaan": "Palpation",
        "Hati": "Liver",
        "Ginjal": "Kidney",
        "Tulang Belakang": "Backbone",
        "Extrimitas": "Extremities",
        "Neurologis": "Neurological",
        "Musculoskeletal": "Musculoskeletal",
        "Buta Warna": "Color Blindness",
        "CARPAL TUNNEL SYNDROME - TINEL TEST": "Carpal Tunnel Syndrome - Tinel Test",
        "CARPAL TUNNEL SYNDROME - PHALEN TEST": "Carpal Tunnel Syndrome - Phalen Test",
        "LOW BACK PAIN - KERNIG TEST": "Low Back Pain - Kernig Test",
        "LOW BACK PAIN - LASEGUE TEST": "Low Back Pain - Lasegue Test",
        "LOW BACK PAIN - PATRICK-KONTRAPATRICK TEST": "Low Back Pain - Patrick-Kontrapatrick Test",
        "LOW BACK PAIN - BRAGARD TEST": "Low Back Pain - Bragard Test",
        "ROMBERG TEST - MATA TERBUKA": "Romberg Test - Eyes Open",
        "ROMBERG TEST - MATA TERTUTUP": "Romberg Test - Eyes Closed",
        "SMELL TEST - SMELL TEST": "Smell Test",
        "Kulit Notes": "Skin Notes",
        "Keadaan Umum Notes": "General Condition Notes",
        "Status Mental Notes": "Mental Status Notes", 
        "Mata Notes": "Eyes Notes",
        "Buta Warna Notes": "Color Blindness Notes",
        "Kelainan Mata Notes": "Eye Abnormalities Notes",
        "Telinga Notes": "Ears Notes",
        "Hidung Notes": "Nose Notes",
        "Tenggorokan Notes": "Throat Notes",
        "Sinus Notes": "Sinus Notes",
        "Tonsil Notes": "Tonsils Notes",
        "Gigi Tidak Normal": "Teeth Abnormal",
        "Kepala & Leher Notes": "Head & Neck Notes",
        "Kelenjar Limfe Notes": "Lymph Nodes Notes",
        "Kelenjar Tiroid/Gondok Notes": "Thyroid/Gland Notes",
        "Dada Notes": "Chest Notes",
        "Jantung Notes": "Heart Notes",
        "Paru Notes": "Lungs Notes",
        "Abdomen Notes": "Abdomen Notes",
        "Perabaan Notes": "Palpation Notes",
        "Hati Notes": "Liver Notes",
        "Ginjal Notes": "Kidney Notes",
        "Tulang Belakang Notes": "Backbone Notes",
        "Extrimitas Notes": "Extremities Notes",
        "Neurologis Notes": "Neurological Notes",
        "Musculoskeletal Notes": "Musculoskeletal Notes",
        "Catatan Lain-lain Kondisi Gigi": "Other Notes on Dental Condition",
        "CARPAL TUNNEL SYNDROME - TINEL TEST Notes": "Carpal Tunnel Syndrome - Tinel Test Notes",
        "CARPAL TUNNEL SYNDROME - PHALEN TEST Notes": "Carpal Tunnel Syndrome - Phalen Test Notes",
        "LOW BACK PAIN - KERNIG TEST Notes": "Low Back Pain - Kernig Test Notes",
        "LOW BACK PAIN - LASEGUE TEST Notes": "Low Back Pain - Lasegue Test Notes",
        "LOW BACK PAIN - PATRICK-KONTRAPATRICK TEST Notes": "Low Back Pain - Patrick-Kontrapatrick Test Notes",
        "LOW BACK PAIN - BRAGARD TEST Notes": "Low Back Pain - Bragard Test Notes",
        "ROMBERG TEST - MATA TERBUKA Notes": "Romberg Test - Eyes Open Notes",
        "ROMBERG TEST - MATA TERTUTUP Notes": "Romberg Test - Eyes Closed Notes",
        "SMELL TEST - SMELL TEST Notes": "Smell Test Notes",
    }
}

VITAL_SIGNS_MAPPING = {
    "id" : {
        "Uses Glasses": "Menggunakan Kacamata",
        "Visus (Ka)": "Visus (Ka)",
        "Spheris Minus (Ka)": "Spheris Minus (Ka)", 
        "Spheris Plus (Ka)": "Spheris Plus (Ka)",
        "Cylinder (Ka)": "Cylinder (Ka)",
        "Axis (Ka)": "Axis (Ka)", 
        "Visus (Ki)": "Visus (Ki)",
        "Spheris Minus (Ki)": "Spheris Minus (Ki)",
        "Spheris Plus (Ki)": "Spheris Plus (Ki)",
        "Cylinder (Ki)": "Cylinder (Ki)",
        "Axis (Ki)": "Axis (Ki)",
        "Tensi (mmHg)": "Tensi (mmHg)",
        "Nadi (X/menit)": "Nadi (X/menit)", 
        "Suhu": "Suhu",
        "SpO2 (%)": "SpO2 (%)",
        "Berat Badan (kg)": "Berat Badan (kg)",
        "Tinggi Badan (cm)": "Tinggi Badan (cm)",
        "Lingkar Perut (cm)": "Lingkar Perut (cm)",
        "BMI": "BMI",
        "Vital Signs Examination Notes": "Catatan Pemeriksaan Tanda Vital",
        "Respiratory Rate (X/menit)": "Laju Pernapasan (X/menit)"
    }, 
    "en" : {
        "Tanda-tanda Vital": "Vital Signs",
        "Visus": "Visual Acuity",
        "Uses Glasses": "Uses Glasses",
        "Visus (Ka)": "Visual Acuity (Right Eye)", 
        "Spheris Minus (Ka)": "Spherical Minus (Right Eye)",
        "Spheris Plus (Ka)": "Spherical Plus (Right Eye)", 
        "Cylinder (Ka)": "Cylinder (Right Eye)",
        "Axis (Ka)": "Axis (Right Eye)",
        "Visus (Ki)": "Visual Acuity (Left Eye)",
        "Spheris Minus (Ki)": "Spherical Minus (Left Eye)",
        "Spheris Plus (Ki)": "Spherical Plus (Left Eye)",
        "Cylinder (Ki)": "Cylinder (Left Eye)", 
        "Axis (Ki)": "Axis (Left Eye)",
        "Tensi (mmHg)": "Blood Pressure (mmHg)",
        "Nadi (X/menit)": "Pulse Rate (bpm)",
        "Suhu": "Temperature",
        "SpO2 (%)": "SpO2 (%)",
        "Berat Badan (kg)": "Weight (kg)",
        "Tinggi Badan (cm)": "Height (cm)", 
        "Lingkar Perut (cm)": "Waist Circumference (cm)",
        "BMI": "BMI",
        "Vital Signs Examination Notes": "Vital Signs Examination Notes",
        "Respiratory Rate (X/menit)": "Respiratory Rate (breaths/min)"
    }
}

OTHER_LABEL_MAPPING = {
    "id" : {
        
    }, 
    "en" : {
        "Hasil Darah": "Blood Test",
        "Urin": "Urine",
        "Tanda Vital": "Vital Signs",
        "Pemeriksaan Fisik": "Physical Examination",
        "Dokter Pemeriksa": "Examiner",
        "Penanggung Jawab Laboratorium": "Laboratory Supervisor",
        "Diperiksa Oleh": "Examined By",
        "Perempuan": "Female",
        "Laki-laki": "Male",
    }
}

LAB_LABEL_MAPPING = {
    "id" : {
        
    }, 
    "en" : {
        # Hematologi Lengkap
        "HEMATOLOGI": "Hematology",
        "Hematologi Lengkap": "Complete Blood Count (CBC)",
        "Hemoglobin (HGB)": "Hemoglobin (HGB)", 
        "Hematokrit (HCT)": "Hematocrit (HCT)",
        "Eritrosit (RBC)": "Red Blood Cells (RBC)",
        "MCV": "Mean Corpuscular Volume (MCV)",
        "MCH": "Mean Corpuscular Hemoglobin (MCH)", 
        "MCHC": "Mean Corpuscular Hemoglobin Concentration (MCHC)",
        "RDW": "Red Cell Distribution Width (RDW)",
        "Trombosit": "Platelets",
        "Leukosit": "White Blood Cells (WBC)",
        "Basofil": "Basophils",
        "Eosinofil": "Eosinophils", 
        "Neutrofil": "Neutrophils",
        "Limfosit": "Lymphocytes",
        "Monosit": "Monocytes",
        "Laju Endap Darah": "Erythrocyte Sedimentation Rate",
        "Golongan Darah/Rhesus": "Blood Type/Rhesus",
        "Fibrinogen": "Fibrinogen",
        "ADP 10": "ADP 10",
        "ADP 5": "ADP 5", 
        "ADP 2": "ADP 2",
        "ADP 1": "ADP 1",
        "Kesimpulan": "Conclusion",

        # Kimia Klinik
        "Kimia Klinik": "Clinical Chemistry",
        "Kimia": "Chemistry",
        "SGOT / AST": "SGOT / AST",
        "SGPT / ALT": "SGPT / ALT", 
        "Gamma-GT": "Gamma-GT",
        "Alkali Fosfotase": "Alkaline Phosphatase",
        "Protein Total": "Total Protein",
        "Albumin": "Albumin",
        "Bilirubin Total": "Total Bilirubin",
        "Bilirubin Direk": "Direct Bilirubin",
        "Bilirubin Indirek": "Indirect Bilirubin",
        "Ureum": "Urea",
        "Kreatinin": "Creatinine",
        "EGFR": "eGFR",
        "Asam Urat": "Uric Acid",
        "Glukosa Puasa": "Fasting Glucose",
        "Glukosa Sewaktu": "Random Blood Glucose",
        "Glukosa 2jpp": "2-Hour Postprandial Glucose",
        "HbA1c (NGSP)": "HbA1c (NGSP)",
        "HbA1c (IFCC)": "HbA1c (IFCC)",
        "Kolesterol Total": "Total Cholesterol",
        "Trigliserida": "Triglycerides",
        "HDL": "HDL",
        "LDL": "LDL",
        "Natrium": "Sodium",
        "Kalium": "Potassium", 
        "Chlorida": "Chloride",
        "Cholinesterase": "Cholinesterase",

        # Imunoserologi
        # Immunoserology
        "Imunoserologi": "Immunoserology",
        "HBsAg": "HBsAg Negative",
        "Anti HAV IgM": "Anti HAV IgM",
        "Anti HBs": "Anti HBs",
        "Vitamin D 25-OH Total": "Vitamin D 25-OH Total",
        "CA 15-3": "CA 15-3",
        "CA 125": "CA 125", 
        "T3 Total": "T3 Total",
        "T4 Total": "T4 Total",

        # Serologi
        "Serologi": "Serology",

        # Mikrobiologi
        "Mikrobiologi": "Microbiology",

        # Kultur Feses & Resistensi
        "Kultur Feses & Resistensi": "Fecal Culture & Resistance",

        # Feses Rutin
        "Feses Rutin": "Routine Stool Examination",
        "Warna": "Color",
        "Konsistensi": "Consistency", 
        "Lendir": "Mucus",
        "Darah": "Blood",
        "Eritrosit": "Erythrocytes",
        "Leukosit": "Leukocytes",
        "Amoeba": "Amoeba",
        "Yeast": "Yeast",
        "Mycelium": "Mycelium",
        "Telur Cacing": "Worm Eggs",
        "Lain-lain": "Others",

        # Makroskopis Urine
        "MAKROSKOPIS URIN": "MACROSCOPIC URINE",
        "Makroskopis urin": "Macroscopic Urine",
        "Makroskopis Urine": "Macroscopic Urinalysis",
        "Warna": "Color",
        "Kejernihan": "Clarity",
        "Berat jenis": "Specific Gravity",
        "Leukosit Negatif": "Leukocytes Negative",
        "Eritrosit Negatif": "Erythrocytes Negative", 
        "Leukosit Esterase": "Leukocyte Esterase",
        "Eritrosit Haem": "Erythrocyte Haem",
        "PH": "pH",
        "Nitrit": "Nitrite",
        "Protein": "Protein",
        "Glukosa": "Glucose",
        "Keton": "Ketone",
        "Urobilinogen": "Urobilinogen",
        "Bilirubin": "Bilirubin",
        "Eritrosit": "Erythrocytes",
        "Leukosit": "Leukocytes",
        "Epitel": "Epithelial",
        "Silinder": "Cast",
        "Kristal": "Crystal",
        "Bakteri": "Bacteria",
        "Lain-lain": "Others",

        # Narkoba
        "Narkoba": "Narcotics",

        # Widal
        "Widal": "Widal",
    }
}


def get_text(key: str, language: str = "id") -> str:
    """
    Get text based on language
    Args:
        key: The text key to lookup
        language: Language code ('id' for Indonesian, 'en' for English)
    Returns:
        Translated text or the key itself if not found
    """
    if language not in LANGUAGE_MAPPING:
        language = "id"  # Default to Indonesian
    
    return LANGUAGE_MAPPING[language].get(key, key) 

def replace_text_label(text: str, language: str = "id", mapping: Any = None) -> str:
    if language not in mapping:
        language = "id"  # Default to English
    
    return mapping[language].get(text, text) 

# replace text satuan
def replace_text_answer(text: str, language: str = "id" ) -> str:
    if language not in LANGUAGE_MAPPING_ANSWER:
        language = "id"  # Default to English
     
    text = LANGUAGE_MAPPING_ANSWER[language].get(text, text)

    return text

def replace_text_satuan(text: str, language: str = "id") -> str:
    if language not in LANGUAGE_MAPPING_SATUAN:
        language = "id"  # Default to English
    
    for key, value in LANGUAGE_MAPPING_SATUAN[language].items():
        text = text.replace(key, value)

    return text

def replace_text_answer_custom(text: str, language: str = "id", mapping: Any = None) -> str:
    if language not in mapping:
        language = "id"  # Default to English
    
    for key, value in mapping[language].items():
        text = text.replace(key, value)

    return text